import type { ReactNode } from 'react'
import type { Position } from '../types/portfolio'
import { fmt, fmtPct, fmtKMBT, clr } from '../utils/format'
import { RangeGauge } from '../components/charts/RangeGauge'
import { InfoTooltip } from '../components/ui/InfoTooltip'
import { HEALTH_COLORS, VALUATION_COLORS, ratingLabel } from '../utils/ratings'

// Shared by the Positions and Watchlist tabs. Both show the same indicators for
// a symbol; only the position-specific columns (quantity, cost, P&L, weight)
// differ, so those stay in PositionsTab.
export type IndicatorKey =
  | 'range'
  | 'pe'
  | 'forwardPe'
  | 'ytd'
  | 'threeYr'
  | 'fiveYr'
  | 'fcf'
  | 'evToEbitda'
  | 'debtToEquity'
  | 'cashFlowQuality'
  | 'health'
  | 'valuation'

export const INDICATOR_COLUMNS: { key: IndicatorKey; label: string }[] = [
  { key: 'range', label: '52 Week Low/High' },
  { key: 'pe', label: 'P/E' },
  { key: 'forwardPe', label: 'Forward P/E' },
  { key: 'ytd', label: 'YTD' },
  { key: 'threeYr', label: '3Y' },
  { key: 'fiveYr', label: '5Y' },
  { key: 'fcf', label: 'FCF' },
  { key: 'evToEbitda', label: 'EV/EBITDA' },
  { key: 'debtToEquity', label: 'Debt/Equity' },
  { key: 'cashFlowQuality', label: 'CF Quality' },
  { key: 'health', label: 'Health' },
  { key: 'valuation', label: 'Valuation' },
]

export const INDICATOR_INFO: Partial<Record<string, string>> = {
  fcf: 'Trailing twelve-month free cash flow — cash generated by operations after capital expenditure. Positive means the business self-funds; negative means it’s burning cash (normal for growth or heavy-capex phases, a warning sign if sustained).',
  evToEbitda: 'Enterprise value ÷ trailing twelve-month EBITDA. Capital-structure neutral valuation multiple (accounts for debt and cash), more comparable across companies with different leverage than P/E.',
  debtToEquity: 'Total debt as a percentage of total equity. Higher values mean more leverage — compare against sector peers rather than an absolute threshold.',
  cashFlowQuality: 'Operating cash flow ÷ net income. Near 1 means earnings are roughly cash-backed (healthy); well below 1 suggests earnings rely on accruals; well above 1 often reflects heavy non-cash charges.',
  health: 'Coarse read on financial soundness from free cash flow, cash flow quality, and debt-to-equity. Says nothing about valuation — pair with the Valuation column.',
  valuation: 'Coarse read on whether the market price looks cheap or expensive, from forward-vs-trailing P/E and EV/EBITDA. Says nothing about financial health — pair with the Health column.',
}

export function ValueWithNote({ value, note }: { value: ReactNode; note?: string }) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, justifyContent: 'flex-end' }}>
      {value}
      {note && <InfoTooltip text={note} />}
    </span>
  )
}

const cell: React.CSSProperties = { padding: '10px 14px', textAlign: 'right', fontFamily: "'DM Mono', monospace", fontSize: 13, color: '#c0c0c0' }
const pill: React.CSSProperties = { padding: '2px 7px', borderRadius: 4, fontSize: 11, fontWeight: 600 }

// IndicatorCells renders one <td> per INDICATOR_COLUMNS entry, in the same
// order, so a caller only has to emit the matching headers.
export function IndicatorCells({ p }: { p: Position }) {
  return (
    <>
      <td style={{ padding: '10px 14px', textAlign: 'right' }}>
        {p.weekLow52 != null && p.weekHigh52 != null && p.currentPrice != null ? (
          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <RangeGauge low={p.weekLow52} high={p.weekHigh52} current={p.currentPrice} />
          </div>
        ) : (
          <span style={{ color: '#555555' }}>—</span>
        )}
      </td>
      <td style={cell}>{p.pe != null && p.pe > 0 ? fmt(p.pe, 1) : '—'}</td>
      <td style={cell}>{p.forwardPE != null && p.forwardPE > 0 ? fmt(p.forwardPE, 1) : '—'}</td>
      <td style={{ ...cell, color: p.ytdReturn != null ? clr(p.ytdReturn) : '#c0c0c0' }}>{p.ytdReturn != null ? fmtPct(p.ytdReturn) : '—'}</td>
      <td style={{ ...cell, color: p.threeYrReturn != null ? clr(p.threeYrReturn) : '#c0c0c0' }}>{p.threeYrReturn != null ? fmtPct(p.threeYrReturn) : '—'}</td>
      <td style={{ ...cell, color: p.fiveYrReturn != null ? clr(p.fiveYrReturn) : '#c0c0c0' }}>{p.fiveYrReturn != null ? fmtPct(p.fiveYrReturn) : '—'}</td>
      <td style={{ ...cell, color: p.fcf != null ? clr(p.fcf) : '#c0c0c0' }}>
        <ValueWithNote value={p.fcf != null ? fmtKMBT(p.fcf) : '—'} note={p.fcfInterpretation} />
      </td>
      <td style={cell}>
        <ValueWithNote value={p.evToEbitda != null && p.evToEbitda !== 0 ? fmt(p.evToEbitda, 1) : '—'} note={p.evToEbitdaInterpretation} />
      </td>
      <td style={cell}>
        <ValueWithNote value={p.debtToEquity != null ? fmt(p.debtToEquity, 1) : '—'} note={p.debtToEquityInterpretation} />
      </td>
      <td style={cell}>
        <ValueWithNote value={p.cashFlowQuality != null && p.cashFlowQuality !== 0 ? fmt(p.cashFlowQuality, 2) : '—'} note={p.cashFlowQualityInterpretation} />
      </td>
      <td style={{ padding: '10px 14px', textAlign: 'right' }}>
        <ValueWithNote
          value={
            p.healthRating ? (
              <span style={{ ...pill, background: (HEALTH_COLORS[p.healthRating] ?? '#555555') + '22', color: HEALTH_COLORS[p.healthRating] ?? '#555555' }}>
                {ratingLabel(p.healthRating)}
              </span>
            ) : (
              <span style={{ color: '#555555' }}>—</span>
            )
          }
          note={p.healthReason}
        />
      </td>
      <td style={{ padding: '10px 14px', textAlign: 'right' }}>
        <ValueWithNote
          value={
            p.valuationRating ? (
              <span style={{ ...pill, background: (VALUATION_COLORS[p.valuationRating] ?? '#555555') + '22', color: VALUATION_COLORS[p.valuationRating] ?? '#555555' }}>
                {ratingLabel(p.valuationRating)}
              </span>
            ) : (
              <span style={{ color: '#555555' }}>—</span>
            )
          }
          note={p.valuationReason}
        />
      </td>
    </>
  )
}
